server:
  port: 80
  error:
    include-stacktrace: never

spring:
  application:
    name: SimbirSoftParserTask

  datasource:
    url: jdbc:hsqldb:file:src/main/resources/db/test; hsqldb.lock_file=false;
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: none

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true


logging:
  level:
    root: ERROR

  file:
    name: logs/mylog.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
