server:
  port: 80
  error:
    include-stacktrace: never

spring:
  application:
    name: SimbirSoftParserTask

  datasource:
    url: jdbc:hsqldb:file:src/main/resources/db/test; hsqldb.lock_file=false;
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: ERROR

  file:
    name: logs/mylog.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
